### ISSUE TITLE
KotlinX compileOnly dependency crashing live clients

### ISSUE THREAD

**Issue by Lumintorious** [SirEdvin/Turtlematic#10]
Can you use `java.time.Instant.now()` instead of `kotlinx.datetime.Clock.System.now()` in the ChunkManager class that handles chunk loading for turtles? This is an external dependency not provided by Forge or even the Kotlin for Forge mod so it crashes the game when not in the development environment.

**Comment by SirEdvin** [comment]
Oh, that is bad. I will try to address it shortly, sorry for this.

**Comment by Lumintorious** [comment]
Thanks a lot for the quick reply :)

**Comment by SirEdvin** [comment]
So, I believe this is fixed as part of 0.7.4 release (actually, only this :) )

**Comment by Lumintorious** [comment]
Is it possible to fix this for the 1.19.4 version?

**Comment by SirEdvin** [comment]
Oh, sure, I will release fix today and probably backport it even further it time.

**Comment by SirEdvin** [comment]
Done :) 

If something doesn't work for some reason, please, report :)
