### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by manaphoenix** [SirEdvin/Turtlematic#14]
I had an automata core in the turtle, and switched it out with the soul scrapper.
not sure which action actually caused the crash, but there ya go.
[crash-2023-07-20_22.23.46-client.txt](https://github.com/SirEdvin/Turtlematic/files/12115691/crash-2023-07-20_22.23.46-client.txt)

**Comment by manaphoenix** [comment]
Update: this crash only happens when I attempt to put my mouse over the automata core. I guess it has something to do with the tooltip. 

likely something that gets set about the core *after* its equipped/used in the turtle.

**Comment by SirEdvin** [comment]
Oh, that's one is tricky to catch. Thanks for reporting!

**Comment by SirEdvin** [comment]
Fixed in 1.1.1
