### ISSUE TITLE
Trutle wont let me type

### ISSUE THREAD

**Issue by IErisI** [SirEdvin/Turtlematic#15]
I am making a small modpack for myself and i try to type but i cant it doesnt let me type inside and i spent hours trying to figure it out i cant :(

**Comment by SirEdvin** [comment]
Can you please provide crashlog or just log from your minecraft run in which you have this issue? 

Please, you https://pastebin.com/ for attaching long texts or just upload file into this issue (or discord)

**Comment by SirEdvin** [comment]
So, this is Visual Overhaul + CC:T compitability issue, there is nothing I can do.

I have created issues ([one](https://github.com/TeamMidnightDust/VisualOverhaul/issues/49) and [two](https://github.com/cc-tweaked/CC-Tweaked/issues/1538)) and probably this issue will be resolved in some way.
