### ISSUE TITLE
Client crashes when a mimic is set to render as a beacon.

### ISSUE THREAD

**Issue by C0mputery** [SirEdvin/Turtlematic#19]
Happens on:
Forge 1.20.1

Steps to reproduce:
Set mimic to a beacon.

Log From Crash:
[Mimic Test Log.txt](https://github.com/SirEdvin/Turtlematic/files/14045525/Mimic.Test.Log.txt)

**Comment by C0mputery** [comment]
I've made a pr to fix this issue 
https://github.com/SirEdvin/Turtlematic/pull/20

**Comment by SirEdvin** [comment]
Fixed in new release
