### ISSUE TITLE
End automata cannot capture blocks

### ISSUE THREAD

**Issue by Totto8492** [SirEdvin/Turtlematic#3]
capture("block") always says "Block is in blacklist".
I think, the conditions seem to be inverted.

https://github.com/SirEdvin/Turtlematic/blob/77aa0bf9acb4300972da88cb1b2406f719492adb/src/main/kotlin/site/siredvin/turtlematic/computercraft/plugins/AutomataCapturePlugin.kt#L116

Minecraft 1.19.2 (Quilt)
Turtlematic 0.5.1

**Comment by SirEdvin** [comment]
Oh, this my less favourite type of bugs, that reminds be that I desperately need a testing system. 
Thanks, I will try to fix it shortly and post a new release

**Comment by SirEdvin** [comment]
And ... done. Fixed in 0.5.2 release

**Comment by Totto8492** [comment]
Thanks!
